rate: 10.0
broadcast:    True
parent_id:   'xtion_optical_frame'
frame_id:    'camera_0_link'


x:     0.00262311
y:     -0.0820151
z:     0.0173944
roll:   2.0688757
pitch: -1.5306075
yaw:   -0.4941516


#parent_id:   'xtion_optical_frame'
#frame_id:    'camera_0_color_optical_frame'

#x:     -0.0124
#y:     -0.0823
#z:     0.01692
#roll:   0.0152272
#pitch: 0.0283539
#yaw:   0.0121376
