rate: 10.0
broadcast:    True
parent_id:   'xtion_optical_frame'
frame_id:    'camera_0_link'


x:     0.0052118
y:     -0.084231
z:     0.001719
roll:   0.9488132
pitch: -1.5543316
yaw:   0.6259723


#parent_id:   'xtion_optical_frame'
#frame_id:    'camera_0_color_optical_frame'

#x:     -0.0098
#y:     -0.0843
#z:     0.00092
#roll:   -0.0137495
#pitch: 0.0066511
#yaw:   0.01099
